### ISSUE TITLE
Issues related to `axom::IndexType`

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#718]
We have several open questions, issues and PRs related to `axom::IndexType`.
This issue is meant to help track the progress in resolving them:

- [ ] Change default for `IndexType` to `int64` ?
- [ ] https://github.com/LLNL/axom/issues/223 (Do we need axom type aliases for native types)
- [ ] https://github.com/LLNL/axom/issues/43 (axom vs. sidre)
- [ ] https://github.com/LLNL/axom/issues/194 (axom vs. sidre, again)
- [ ] https://github.com/LLNL/axom/issues/295 (more flexibility in quest In/Out)
- [ ] https://github.com/LLNL/axom/pull/628 (usage in `axom::Map`)

General search: https://github.com/LLNL/axom/issues?q=IndexType

---

`axom::IndexType` is controlled by the following config option:
https://github.com/LLNL/axom/blob/3d962ad30f8610c180e6d742e7c5e0cab4b6619d/src/cmake/AxomOptions.cmake#L12

It is defined here
https://github.com/LLNL/axom/blob/3d962ad30f8610c180e6d742e7c5e0cab4b6619d/src/axom/core/Types.hpp#L47-L51

**Comment by rhornung67** [comment]
I definitely think we should converge to a single index type definition used throughout axom for the default case.

Do we ever think we would need to support different sized index types for different axom components; e.g., int32 for one and int64 for another? If so, we should build this in along side the other points in this issue.
